AllCops:
  Excludes:
    - db/**

Style/FrozenStringLiteralComment:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/MixinUsage:
  Exclude:
   - 'bin/setup'
   - 'bin/update'

Metrics/LineLength:
  Max: 130

Metrics/MethodLength:
  Max: 15

Metrics/BlockLength:
  Exclude:
    - 'Rakefile'
    - '**/*.rake'
    - 'spec/**/*.rb'

Metrics/ModuleLength:
  Exclude:
    - 'spec/**/*.rb'

Lint/AmbiguousBlockAssociation:
  Exclude:
    - 'spec/**/*.rb'

Lint/InterpolationCheck:
  Exclude:
    - 'spec/**/*.rb'